apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitolite.fullname" . }}
  labels:
    {{- include "gitolite.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gitolite.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gitolite.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gitolite.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SSH_KEY
              value: "{{ default "" .Values.git.admin.key}}"
            - name: SSH_KEY_NAME
              value: "{{ default "admin" .Values.git.admin.name}}"
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          volumeMounts:
            - name: repos
              mountPath: /var/lib/git/repositories
            - name: config
              mountPath: /var/lib/git/.gitolite.rc
              subPath: .gitolite.rc
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
        - name: setup
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - "/bin/sh"
            - "-c"
            - >-
              gitolite print-default-rc | awk '/UMASK/{ $3="0022," }; { print }' - > /config/.gitolite.rc
          volumeMounts:
            - name: config
              mountPath: /config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: repos
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "gitolite.fullname" .) }}
        - name: config
          emptyDir: {}
      {{- end }}
