apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitolite.fullname" . }}
  labels:
    {{- include "gitolite.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    {{- include "gitolite.selectorLabels" . | nindent 4 }}
