namespace: devel

releases:
  # Gitolite
  - name: gitolite
    chart: ./charts/gitolite
    values:
      - values/gitolite.yaml.gotmpl

  # CGit
  - name: cgit
    chart: ./charts/cgit
    values:
      - values/cgit.yaml.gotmpl

values:
  - .env.{{ .Environment.Name }}.yaml
